export const models = [
    {
        name:"house",
        offset:15,
        scalling:7
    },
    {
        name:"cat",
        offset:5,
        scalling:3
    },
    {
        name:"fountain",
        offset:10,
        scalling:0.5
    },
    {
        name:"campfire",
        offset:5,
        scalling:0.01
    },
    {
        name:"car",
        offset:3,
        scalling:1
    },
    {
        name:"slide",
        offset:2,
        scalling:1
    },
    {
        name:"gas_station",
        offset:10,
        scalling:1
    },
    {
        name:"convenience_store",
        offset:3,
        scalling:1
    },
    {
        name:"building01",
        offset:13,
        scalling:5
    },
    {
        name:"city_park",
        offset:10,
        scalling:0.7
    },
    {
        name:"buisness_man",
        offset:5,
        scalling:1
    }
];