export const models = [
    {
        name:"house",
        offset:15,
        scalling:3
    },
    {
        name:"cat",
        offset:1,
        scalling:10
    },
    {
        name:"fountain",
        offset:10,
        scalling:1
    },
    {
        name:"low_poly_camp_fire",
        offset:10,
        scalling:0.01
    }
];