export const models = [
    {
        name:"house",
        offset:15,
        scalling:7
    },
    {
        name:"cat",
        offset:5,
        scalling:10
    },
    {
        name:"fountain",
        offset:10,
        scalling:0.5
    },
    {
        name:"campfire",
        offset:5,
        scalling:0.01
    }
];